CREATE TABLE IF NOT EXISTS plugin_installs (
id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,title TEXT NOT NULL,version TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,manifest TEXT NOT NULL,installed_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS theme_installs (
id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,title TEXT NOT NULL,version TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 0,manifest TEXT NOT NULL,installed_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS plugin_settings (
plugin_id TEXT NOT NULL,key TEXT NOT NULL,value TEXT,PRIMARY KEY(plugin_id,key));
CREATE TABLE IF NOT EXISTS widget_instances (
id TEXT PRIMARY KEY,sidebar TEXT NOT NULL,widget_type TEXT NOT NULL,title TEXT,config TEXT,sort_order INTEGER NOT NULL DEFAULT 0,enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS shortcodes (
id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,enabled INTEGER NOT NULL DEFAULT 1,config TEXT);
